project:
  type: manuscript

execute:
  freeze: auto

format:
  apaquarto-html:
    toc: true
  apaquarto-docx:
    toc: false
  apaquarto-typst:
    toc: false
    list-of-figures: false
    list-of-tables: false
  apaquarto-pdf:
    documentmode: man
    keep-tex: false
#format:
#  html:
#    toc: true
#    comments:
#      hypothesis: true
  #docx: default
  #jats: default
  #agu-pdf: default
  #apaquarto-docx: default
  #apaquarto-html: default
  #apaquarto-pdf: default
  #apaquarto-typst: default
