project:
  type: manuscript

execute:
  freeze: auto

format:
  apaquarto-html:
    toc: true
#format:
#  html:
#    toc: true
#    comments:
#      hypothesis: true
  #docx: default
  #jats: default
  #agu-pdf: default
  #apaquarto-docx: default
  #apaquarto-html: default
  #apaquarto-pdf: default
  #apaquarto-typst: default
